# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6958ec4a5a91a6deb1fb34f0c98db148d9048cf5f5d38b22bb78f7d326afe64aac16de254a411da9ac8dc107cf7e800e00014be83634adc4cbfcada45da6d83a

test:
  secret_key_base: fbf51316e23a3f7018ab1a0fc1eed073e53af2af33234b0a90d8deabfe4868198d2c8fa3f4c57f1b46151c390baa4900fc85bd9878ab6b2b534f3aad3c51221f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
